In [3]:
import cv2
import numpy as np

In [15]:
#initializing the camera
cap=cv2.VideoCapture(0)
#creating a classifier object - Face Detection 
face_cascade=cv2.CascadeClassifier(r"C:\Users\dell\Desktop\projects\Machine Learning\CBMC\Real Time Face Recognition\haarcascade_frontalface_default.xml")
skip=0
face_data=[]
dataset_path=r"C:\Users\dell\Desktop\projects\Machine Learning\Coding Blocks\Real Time Face Recognition"
filename=input("enter name of person whose face you're scanning:")

while True:
    ret,frame=cap.read()  #frame represents an image(series)
    gray_frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)      

    if ret==False:
        continue
    #giving an image to the model
    faces=face_cascade.detectMultiScale(gray_frame,1.3,5)
    #sorting according to area=w*h
    faces=sorted(faces,key=lambda f:f[2]*f[3],reverse=True)
    #faces will return us the (x,y,w,h) of the face
    #now we need to make a boundary of rectange around the image
    for face in faces[0:1]:
        x,y,w,h=face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        
        #cropping the region of interest
        offset=10
        face_section=frame[y-offset:y+h+offset,x-offset:x+w+offset]
        face_section=cv2.resize(face_section,(100,100)) 
        if(skip%10==0):
            face_data.append(face_section)
            print(len(face_data))
        skip+=1   #after every 10th frame , we're increasing count by 1
    
    
    cv2.imshow("Video Frame",frame)
    #cv2.imshow("gray frame",gray_frame)
    cv2.imshow("face_section",face_section)
    
    key=cv2.waitKey(1) & 0xFF
    if key==ord('q'):
        break
        
#converting our face_data to numpy array
face_data=np.asarray(face_data)
face_data=face_data.reshape((face_data.shape[0],-1))
print(face_data.shape)
#saving the data
np.save(r"C:\Users\dell\Desktop\projects\Machine Learning\Coding Blocks\Real Time Face Recognition"+"\\"+filename+".npy",face_data)
cap.release()  
cv2.destroyAllWindows()
        

enter name of person whose face you're scanning:yash
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
(27, 30000)


In [ ]:
#face_data.shape

In [12]:
a=[[[1,2],[2,3]],[[4,5],[6,7]]]
a=np.array(a)
a.flatten()

array([1, 2, 2, 3, 4, 5, 6, 7])

In [5]:
a=np.concatenate(a,axis=0)

In [6]:
a

array([[1, 2],
       [2, 3],
       [4, 5],
       [6, 7]])

In [7]:
a[0]

array([1, 2])